### PR TITLE
fix: STRF-11523 Enable dynamic partials

### PR DESCRIPTION
**Pull request by jairo-bc**
#### What?

Fixed regex that allows to add partials with syntax `{{#> components/ul }}`

#### Tickets / Documentation

-   [STRF-11523](https://bigcommercecloud.atlassian.net/browse/STRF-11523)

#### Screenshots (if appropriate)
Screenshot 2024-12-16 at 18 42 21
Screenshot 2024-12-16 at 18 42 24

#### QA Steps:
1) Get ready to run stencil start (load theme locally, stencil init, etc.)
2) Run **stencil start**
3) Create a similiar structure of components like [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/c.html,  [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/pages/page.3.html), [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/li.html) and [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/ul.html)
4) Observe that list successfully rendered in the browser

cc @bigcommerce/storefront-team

[STRF-11523]: https://bigcommercecloud.atlassian.net/browse/STRF-11523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by jmwiese — COMMENTED** [review]
LGTM

**Comment by bc-max** [comment]
@jairo-bc I see this error in a terminal when running stencil locally (node 20):

```
Error: The following template(s) are/is missing: 
components/li
components/li
components/li
components/ul
    at file:///.../stencil-cli/lib/template-assembler.js:121:17
    at wrapper (/.../stencil-cli/node_modules/async/dist/async.js:272:20)
    at iteratorCallback (/.../stencil-cli/node_modules/async/dist/async.js:502:17)
    at /.../stencil-cli/node_modules/async/dist/async.js:328:20
    at wrapper (/.../stencil-cli/node_modules/async/dist/async.js:272:20)
    at iteratorCallback (/.../stencil-cli/node_modules/async/dist/async.js:502:17)
    at /.../stencil-cli/node_modules/async/dist/async.js:328:20
    at ReadFileContext.<anonymous> (file:///.../stencil-cli/lib/template-assembler.js:139:17)
    at ReadFileContext.callback (/.../stencil-cli/node_modules/graceful-fs/graceful-fs.js:123:16)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (node:fs:299:13)
```

**Comment by jairo-bc** [comment]
@bc-max did you create it? I just updated the description for all necessary components to have

**Review by bc-max — APPROVED** [review]
LGTM 💚 

image

**Pull request merged**
