### PR TITLE
STENCIL-3480 Simplify and fix BrowserSync css reload issue

### PR DESCRIPTION
**Pull request by mcampa**
- Fixes: https://github.com/bigcommerce/stencil-cli/issues/284

Jira: https://jira.bigcommerce.com/browse/STENCIL-3480

@bigcommerce/stencil-team

### CODE REVIEW

**Comment by willfaught** [comment]
Looking

**Comment by willfaught** [comment]
Can you explain why these changes fix that problem?

**Comment by mcampa** [comment]
We changed the css urls recently. So the way we were calling `BrowserSync.reload()` was wrong. And then I found that we don't need to pass the css file path because since version 2.6.0 we can use wildcards.

https://www.browsersync.io/docs/api#api-reload

**Comment by Bshally** [comment]
Injection works now, thanks! I've created an issue for a bug occurring after this issue: [#309](https://github.com/bigcommerce/stencil-cli/issues/309)

**Pull request merged**
