### PR TITLE
feat: strf-9345 Infer apiHost from storeUrl

### PR DESCRIPTION
**Pull request by jmwiese**
[STRF-9345](https://jira.bigcommerce.com/browse/STRF-9345)

#### What?

Attempt to infer the apiHost from the storeUrl for integration/staging stores, falling back to API_HOST constant otherwise.

apiHost is now saved in the stencil config and loaded from there instead of just the API_HOST

@jairo-bc

### CODE REVIEW

**Comment by bookernath** [comment]
Instead of doing this implicitly, why not just accept an argument on `stencil init` to indicate the environment? Default would be prod, naturally, if not specified.

**Comment by jmwiese** [comment]
@bookernath yeah I can add that, or `--host` can be provided during `stencil start` which is how it works currently. However if someone is trying to test against an integration or staging store (the majority of which will just have a my-integration/my-staging.zone url), why not also try to infer? Because otherwise it will never work.

**Comment by jairo-bc** [comment]
I would suggest to have both `--host` option and inferring, so it will be backward compatible with what we have now. But in this case we need to decide what priority should be.

**Comment by jmwiese** [comment]
@jairo-bc yeah this PR should allow both. It will save the inferred host to the config file. Then during operations like `stencil start`, etc it should prioritize the `--host` option before falling back to the apiHost saved in the config file.

**Review by jairo-bc — APPROVED** [review]

**Comment by jairo-bc** [comment]
LGTM

**Pull request merged**
