### PR TITLE
feat: update browser sync to use latest master

### PR DESCRIPTION
**Pull request by junedkazi**
#### What?
update browser sync to use latest master

@bigcommerce/storefront-team

### CODE REVIEW

**Comment by lord2800** [comment]
I know there was some reason we haven't done this until now, @bookernath might have more info?

**Comment by bookernath** [comment]
You can see the history here:

https://github.com/bigcommerce/stencil-cli/pulls?utf8=%E2%9C%93&q=is%3Apr+browser-sync

I tried to do this before, but we reverted it because we thought it was causing a bug. I forget the details of the bug - @bc-williamkwon do you recall?

**Comment by junedkazi** [comment]
hot reload was broken for css. I am testing it right now and if there is a bug I do plan to fix it.

**Comment by bookernath** [comment]
I see in https://github.com/bigcommerce/stencil-cli/pull/512 we said it breaks "CSS hot reloading".

**Pull request merged**
