### PR TITLE
stencil-styles version bump for nodejs 8

### PR DESCRIPTION
**Pull request by mcampa**
This will allow users to use `stencil-cli` with Node.js 8 only for rendering (`stencil start`)

`stencil bundle` is not working yet due to this issue https://github.com/archiverjs/node-archiver/issues/236

@bigcommerce/stencil-team

### CODE REVIEW

**Comment by willfaught** [comment]
How does it do that?

**Comment by mcampa** [comment]
https://github.com/bigcommerce/stencil-styles/pull/26

**Comment by willfaught** [comment]
Neat! How do those changes relate to this diff?

**Comment by mcampa** [comment]
This is bumping the version of `@bigcommerce/stencil-styles` I think is pretty obvious.

The new version of `@bigcommerce/stencil-styles` supports node 8

**Comment by willfaught** [comment]
Yep. Proof that that's the correct version to bump to?

**Comment by mcampa** [comment]
I don't understand you comments, what proof do you need? 
Is a simple version bump. Travis is passing, the latest version of `@bigcommerce/stencil-styles` is 1.1.0. Here is the proof https://www.npmjs.com/package/@bigcommerce%2Fstencil-styles

**Comment by willfaught** [comment]
>the latest version of @bigcommerce/stencil-styles is 1.1.0. Here is the proof https://www.npmjs.com/package/@bigcommerce%2Fstencil-styles

Perfect, thanks. LGTM.

**Pull request merged**
